Update Documentation on tfe_policy_set
The tfe_policy_set resource requires an Oauth token ID, but the documentation says to use the Oauth client ID. When you do that in your own code, you'll get the following error:

```
Error: Error creating policy set policy-set-name for organization my-organization: unprocessable entity

OAuth token does not exist
```